### ISSUE TITLE
User management Module

### ISSUE THREAD

**Issue by azaraelcorpin** [azaraelcorpin/TER-FE#2]
Create display for user management Module

```

1.     to manage top level user.
2.     to identify the user (evaluator) upon log in to redirect to appropriate page display.
3.     User management can be accessed only by admin users.
4.     For Dean, Chairperson, and admin only..
5.     Only 1 record for Dean.
6.     Only 1 record for Chairperson.
7.     Admin can be multiple
```

**ROLES**

```
    Set admin user
    Set Dean's account
    Set Chairperson's account
```

**Model**
create k12_users model
```

    id autoIncreament
    email
    position (admin/dean/chairperson)
```

**API's**

setAsDean(email)
setAsChairperson(email)
setAsAdmin(email)
removeAsAdmin(email)
getList() -->return list of record in the k12_users model

**Todo**

- [ ] Create Route link from sidebar
- [ ] Create Module Page
    - [ ] Create table with the following header:
         - [ ] email
         - [ ] Position
         - [ ] Action _(for update/remove purpose)_
   - [ ] Create New User Button
- [ ] Create New User Form (_Dialog_)

![Image](https://user-images.githubusercontent.com/117239609/220496074-28794797-7288-4aad-b955-d5de65c0be09.png)
