### ISSUE TITLE
TER schedule Management Module

### ISSUE THREAD

**Issue by azaraelcorpin** [azaraelcorpin/TER-FE#3]
Create display for TER schedule management Module.

1. to manage TER evaluation schedule
2. can be accessed only by admin users.
3. one record only per school-year(sy)

**ROLES**

    Set k12 TER schedule

**Model**
create k12_ter_schedule model

    id autoIncreament
    date_start
    date_end
    sy
    status _(open/closed)_
    updated_by
    date_updated

**API's**

createEvaluationSched( _parameters see model_)
updateEvaluationSched ( _parameters see model_)
getEvaluationSchedList

**Todo**

- [ ] Create Route link from sidebar
- [ ] Create Module Page
    - [ ] Create table with the following header:
         - [ ] Schoolyear(sy)
         - [ ] start Date
         - [ ] end Date
         - [ ] Status
         - [ ] Updated by
         - [ ] Date Updated
         - [ ] Action _(for update purpose)_
   - [ ] Create New Evaluation Schedule Button
- [ ] Create New Evaluation Schedule Form _(Dialog)_
